#!/usr/bin/env python3
"""Generate compact C++ sparse-cell maps for the SIDIS tranche plugins."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any, Iterable


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "analyses/rivet/dis/SIDISTrancheBinning.hh"


def _reference(measurement: str) -> dict[str, Any]:
    return json.loads((ROOT / f"data/phenomenology/{measurement}/reference.json").read_text())


def _values(point: dict[str, Any], dimensions: Iterable[str]) -> list[float]:
    result: list[float] = []
    for dimension in dimensions:
        result.extend([float(point[f"{dimension}_low"]), float(point[f"{dimension}_high"])])
    return result


def _initializer(rows: list[list[float]]) -> str:
    return "\n".join(
        "      {" + ", ".join(format(value, ".17g") for value in row) + "},"
        for row in rows
    )


def _function(name: str, typename: str, rows: list[list[float]]) -> str:
    return f'''  inline const std::vector<{typename}>& {name}() {{
    static const std::vector<{typename}> cells = {{
{_initializer(rows)}
    }};
    return cells;
  }}
'''


def main() -> None:
    payload: dict[str, list[list[float]]] = {}
    for measurement in ("COMPASS_2025_I2840545", "COMPASS_2026_I3096394"):
        reference = _reference(measurement)
        tag = "compass2025" if "2025" in measurement else "compass2026"
        for species, dataset in reference["datasets"].items():
            payload[f"{tag}_{species}"] = [
                _values(point, ("x", "y", "z")) for point in dataset["points"]
            ]
    pt_reference = _reference("COMPASS_2018_I1624692")
    for species, dataset in pt_reference["datasets"].items():
        payload[f"compass2018_{species}"] = [
            _values(point, ("x", "q2", "z", "pt2")) for point in dataset["points"]
        ]
    hermes = _reference("HERMES_2013_I1208547")
    for config in hermes["binnings"]:
        dataset = hermes["datasets"][f"H_piplus_{config.replace('-', '_')}"]
        rows: list[list[float]] = []
        for point in dataset["points"]:
            if config == "zQ2-3D":
                rows.append(_values(point, ("x", "q2", "z", "phperp")))
            else:
                rows.append(_values(point, ("x",)) + [0.0, 1.0e100]
                            + _values(point, ("z", "phperp")))
        payload[f"hermes_{config.replace('-', '_').lower()}"] = rows

    digest = hashlib.sha256(json.dumps(payload, separators=(",", ":"),
                                       sort_keys=True).encode()).hexdigest()
    functions: list[str] = []
    for name, rows in payload.items():
        typename = "XYZCell" if name.startswith("compass20") and "2018" not in name else "XQ2ZTransverseCell"
        functions.append(_function(name + "Cells", typename, rows))
    content = f'''// -*- C++ -*-
// Generated by scripts/generate_sidis_tranche_binning.py.
// Sparse-cell payload SHA256: {digest}
#pragma once

#include <cmath>
#include <vector>

namespace Rivet {{
namespace SIDISTrancheBinning {{

  struct XYZCell {{
    double xLow, xHigh, yLow, yHigh, zLow, zHigh;
  }};

  struct XQ2ZTransverseCell {{
    double xLow, xHigh, q2Low, q2High, zLow, zHigh, transverseLow, transverseHigh;
  }};

{chr(10).join(functions)}
  inline bool inHalfOpen(double value, double low, double high) {{
    return value >= low && (value < high || std::abs(value-high) < 1.0e-12);
  }}

  inline bool matchesDIS(const XYZCell& cell, double x, double y) {{
    return inHalfOpen(x, cell.xLow, cell.xHigh) &&
           inHalfOpen(y, cell.yLow, cell.yHigh);
  }}

  inline int findCell(const std::vector<XYZCell>& cells,
                      double x, double y, double z) {{
    for (size_t index = 0; index < cells.size(); ++index) {{
      const auto& cell = cells[index];
      if (matchesDIS(cell, x, y) && inHalfOpen(z, cell.zLow, cell.zHigh))
        return int(index);
    }}
    return -1;
  }}

  inline bool matchesDIS(const XQ2ZTransverseCell& cell,
                         double x, double q2) {{
    return inHalfOpen(x, cell.xLow, cell.xHigh) &&
           inHalfOpen(q2, cell.q2Low, cell.q2High);
  }}

  inline int findCell(const std::vector<XQ2ZTransverseCell>& cells,
                      double x, double q2, double z, double transverse) {{
    for (size_t index = 0; index < cells.size(); ++index) {{
      const auto& cell = cells[index];
      if (matchesDIS(cell, x, q2) && inHalfOpen(z, cell.zLow, cell.zHigh) &&
          inHalfOpen(transverse, cell.transverseLow, cell.transverseHigh))
        return int(index);
    }}
    return -1;
  }}

}} // namespace SIDISTrancheBinning
}} // namespace Rivet
'''
    OUTPUT.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
