#!/usr/bin/env python3
"""Generate the exact sparse COMPASS 2017 cell maps used by Rivet."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "analyses" / "rivet" / "dis" / "COMPASSSIDISBinning.hh"


def _cells(measurement: str) -> list[list[float]]:
    snapshot = json.loads(
        (ROOT / "data" / "phenomenology" / measurement / "reference.json")
        .read_text(encoding="utf-8")
    )
    return [[float(value) for value in row] for row in snapshot["valid_cell_map"]]


def _initializer(cells: list[list[float]]) -> str:
    return "\n".join(
        "      {" + ", ".join(format(value, ".17g") for value in row) + "},"
        for row in cells
    )


def main() -> None:
    pion = _cells("COMPASS_2017_I1444985")
    kaon = _cells("COMPASS_2017_I1483098")
    digest = hashlib.sha256(
        json.dumps({"pion": pion, "kaon": kaon}, separators=(",", ":")).encode()
    ).hexdigest()
    output = f'''// -*- C++ -*-
// Generated by scripts/generate_compass_sidis_binning.py.
// Sparse-cell payload SHA256: {digest}
#pragma once

#include <cmath>
#include <vector>

namespace Rivet {{
namespace COMPASSSIDIS {{

  struct MultiplicityCell {{
    double xLow, xHigh, yLow, yHigh, zLow, zHigh;
  }};

  inline const std::vector<MultiplicityCell>& pionHadronCells() {{
    static const std::vector<MultiplicityCell> cells = {{
{_initializer(pion)}
    }};
    return cells;
  }}

  inline const std::vector<MultiplicityCell>& kaonCells() {{
    static const std::vector<MultiplicityCell> cells = {{
{_initializer(kaon)}
    }};
    return cells;
  }}

  inline bool inHalfOpen(double value, double low, double high) {{
    return value >= low && (value < high ||
      (std::abs(high - 0.85) < 1.0e-12 && value <= high));
  }}

  inline bool matchesDIS(const MultiplicityCell& cell, double x, double y) {{
    return inHalfOpen(x, cell.xLow, cell.xHigh) &&
           inHalfOpen(y, cell.yLow, cell.yHigh);
  }}

  inline int findCell(const std::vector<MultiplicityCell>& cells,
                      double x, double y, double z) {{
    for (size_t index = 0; index < cells.size(); ++index) {{
      const MultiplicityCell& cell = cells[index];
      if (matchesDIS(cell, x, y) && inHalfOpen(z, cell.zLow, cell.zHigh))
        return int(index);
    }}
    return -1;
  }}

}} // namespace COMPASSSIDIS
}} // namespace Rivet
'''
    OUTPUT.write_text(output, encoding="utf-8")


if __name__ == "__main__":
    main()
